services:
  app:
    build:
      target: dev
    environment:
      APP_ENV: dev
      XDEBUG_MODE: debug,develop
      XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9003 idekey=PHPSTORM"
    ports:
      - "9003:9003"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/99-opcache.ini:ro
      - ./docker/php/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro
