services:
    app:
        build:
            target: dev
            context: .
            dockerfile: Dockerfile
        image: mvc_template-php-fpm
        container_name: mvc_template_app
        restart: unless-stopped
        environment:
            SERVER_NAME: ${SERVER_NAME:-localhost}
            PHP_INI_MEMORY_LIMIT: 512M

    nginx:
        image: nginx:stable-alpine
        container_name: mvc_template_nginx
        restart: unless-stopped
        ports:
            - "8111:80"
        volumes:
            - .:/var/www/html:ro
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - db

    db:
        image: mariadb:10.11
        container_name: mvc_template_db
        ports:
            - "3308:3306"
        volumes:
            - db-data:/var/lib/mysql
            - ./docker/db/init:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: 'root_password'
            MYSQL_DATABASE: 'mydatabase'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'pass'
volumes:
    db-data:
    mvc_template-data:
