services:
    app:
        build:
            target: dev
            context: .
            dockerfile: Dockerfile
        image: mvc_template-php-fpm
        container_name: mvc_template_app
        restart: unless-stopped
        environment:
            SERVER_NAME: ${SERVER_NAME:-localhost}
            PHP_INI_MEMORY_LIMIT: 512M

    nginx:
        image: nginx:stable-alpine
        container_name: mvc_template_nginx
        restart: unless-stopped
        ports:
            - "8111:80"
        volumes:
            - .:/var/www/html:ro
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - db
            - app

    db:
        image: postgres:${POSTGRES_VERSION:-16}-alpine
        container_name: mvc_template_db
        restart: unless-stopped
        ports:
            - "5433:5432"
        volumes:
            - db-data:/var/lib/postgresql/data:rw
            - ./docker/db/init:/docker-entrypoint-initdb.d:ro
        env_file:
            - .env
            - .env.local
        healthcheck:
            test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
            timeout: 5s
            retries: 5
            start_period: 60s
volumes:
    db-data:
    mvc_template-data:
